// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Waveshare-RP2040-Touch-LCD-1.28

#ifndef _WAVESHARE_RP2040_TOUCH_LCD_1_28_UI_COMP_HOOK_H
#define _WAVESHARE_RP2040_TOUCH_LCD_1_28_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_Hour_group_create_hook( lv_obj_t *comp );

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
