// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Waveshare-RP2040-Touch-LCD-1.28

#ifndef _UI_COMP_HOUR_GROUP_H
#define _UI_COMP_HOUR_GROUP_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Hour group
#define UI_COMP_HOUR_GROUP_HOUR_GROUP 0
#define _UI_COMP_HOUR_GROUP_NUM 1
lv_obj_t *ui_Hour_group_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
