// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Waveshare-RP2040-Touch-LCD-1.28

#include "../ui.h"

void ui_ScrClock_screen_init(void)
{
    ui_ScrClock = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrClock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScrClock, &ui_img_background_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_ScrClock);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, -8);
    lv_obj_set_y(ui_Button1, 64);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Click");

    ui_ImgSeconde = lv_img_create(ui_ScrClock);
    lv_img_set_src(ui_ImgSeconde, &ui_img_sec_dot_png);
    lv_obj_set_width(ui_ImgSeconde, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgSeconde, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgSeconde, 0);
    lv_obj_set_y(ui_ImgSeconde, -115);
    lv_obj_set_align(ui_ImgSeconde, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgSeconde, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgSeconde, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_ImgSeconde, 4, 118);

    ui_LbMinute00 = lv_label_create(ui_ScrClock);
    lv_obj_set_width(ui_LbMinute00, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbMinute00, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbMinute00, 45);
    lv_obj_set_y(ui_LbMinute00, 6);
    lv_obj_set_align(ui_LbMinute00, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbMinute00, "27");
    lv_obj_set_style_text_color(ui_LbMinute00, lv_color_hex(0xEE1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbMinute00, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbMinute00, &ui_font_Montserrat_light_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GpHour = lv_obj_create(ui_ScrClock);
    lv_obj_set_width(ui_GpHour, 135);
    lv_obj_set_height(ui_GpHour, 135);
    lv_obj_clear_flag(ui_GpHour, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GpHour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GpHour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_GpHour, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GpHour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbHour0h = lv_label_create(ui_GpHour);
    lv_obj_set_width(ui_LbHour0h, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbHour0h, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbHour0h, -38);
    lv_obj_set_y(ui_LbHour0h, 22);
    lv_obj_set_align(ui_LbHour0h, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LbHour0h, "0");
    lv_obj_set_style_text_color(ui_LbHour0h, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbHour0h, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbHour0h, &ui_font_Montserrat_light_120, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbHourh0 = lv_label_create(ui_GpHour);
    lv_obj_set_width(ui_LbHourh0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbHourh0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbHourh0, 41);
    lv_obj_set_y(ui_LbHourh0, 21);
    lv_obj_set_align(ui_LbHourh0, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LbHourh0, "3");
    lv_obj_set_style_text_color(ui_LbHourh0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbHourh0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbHourh0, &ui_font_Montserrat_light_120, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtGoToWeatherScreen = lv_obj_create(ui_ScrClock);
    lv_obj_set_width(ui_BtGoToWeatherScreen, 48);
    lv_obj_set_height(ui_BtGoToWeatherScreen, 50);
    lv_obj_set_x(ui_BtGoToWeatherScreen, 88);
    lv_obj_set_y(ui_BtGoToWeatherScreen, 62);
    lv_obj_set_align(ui_BtGoToWeatherScreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BtGoToWeatherScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtGoToWeatherScreen, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtGoToWeatherScreen, lv_color_hex(0xEE1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtGoToWeatherScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtGoToWeatherScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtGoToWeatherScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtGoToWeatherScreen, lv_color_hex(0xEE1E1E), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BtGoToWeatherScreen, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ImgWeather = lv_img_create(ui_BtGoToWeatherScreen);
    lv_img_set_src(ui_ImgWeather, &ui_img_weather_png);
    lv_obj_set_width(ui_ImgWeather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgWeather, -8);
    lv_obj_set_y(ui_ImgWeather, -6);
    lv_obj_set_align(ui_ImgWeather, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgWeather, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgWeather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgArc = lv_img_create(ui_BtGoToWeatherScreen);
    lv_img_set_src(ui_ImgArc, &ui_img_btn_bg_3_png);
    lv_obj_set_width(ui_ImgArc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgArc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgArc, 5);
    lv_obj_set_y(ui_ImgArc, 2);
    lv_obj_set_align(ui_ImgArc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgArc, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgArc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PnlCalendar = lv_obj_create(ui_ScrClock);
    lv_obj_set_width(ui_PnlCalendar, 100);
    lv_obj_set_height(ui_PnlCalendar, 50);
    lv_obj_set_x(ui_PnlCalendar, 40);
    lv_obj_set_y(ui_PnlCalendar, -64);
    lv_obj_set_align(ui_PnlCalendar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlCalendar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PnlCalendar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlCalendar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PnlCalendar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PnlCalendar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbDayOfWeek = lv_label_create(ui_PnlCalendar);
    lv_obj_set_width(ui_LbDayOfWeek, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbDayOfWeek, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbDayOfWeek, -20);
    lv_obj_set_y(ui_LbDayOfWeek, -15);
    lv_obj_set_align(ui_LbDayOfWeek, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbDayOfWeek, "MON");
    lv_obj_set_style_text_color(ui_LbDayOfWeek, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbDayOfWeek, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbDayOfWeek, &ui_font_Montsererat_bold_12_extended, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbDate = lv_label_create(ui_PnlCalendar);
    lv_obj_set_width(ui_LbDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbDate, -15);
    lv_obj_set_y(ui_LbDate, 0);
    lv_obj_set_align(ui_LbDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbDate, "18 FEB");
    lv_obj_set_style_text_color(ui_LbDate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbDate, &ui_font_Montserrat_medium_12_extended, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbYear = lv_label_create(ui_PnlCalendar);
    lv_obj_set_width(ui_LbYear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbYear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbYear, -21);
    lv_obj_set_y(ui_LbYear, 14);
    lv_obj_set_align(ui_LbYear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbYear, "2022");
    lv_obj_set_style_text_color(ui_LbYear, lv_color_hex(0x6B6B6B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbYear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbYear, &ui_font_Montserrat_medium_12_extended, LV_PART_MAIN | LV_STATE_DEFAULT);

}
