name: Build ESP8266
on: [workflow_call]
jobs:
  Compute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install platform
        run: |
          arduino-cli core update-index          
          arduino-cli core install esp8266:esp8266 --additional-urls http://arduino.esp8266.com/stable/package_esp8266com_index.json

      - name: Compile Sketch
        run: arduino-cli compile --config-file ./scripts/arduino-cli.esp8266.yaml --fqbn esp8266:esp8266:generic ./src/core/core.ino
        