name: CI
on: [push, pull_request]
jobs:
  Lint:
    uses: ./.github/workflows/lint.yml

  Check-Style:
    uses: ./.github/workflows/check-style.yml

  Build-ESP8266:
    uses: ./.github/workflows/build.esp8266.yml
  
  Build-RP2040:
    uses: ./.github/workflows/build.rp2040.yml